name: SHS Z2M Presence Zone Configurator
version: "2.6.3"
slug: shs_z2m_presence_zones
description: Web-based zone configurator for SHS01 mmWave presence sensor via Zigbee2MQTT
url: https://github.com/notownblues/SHS-Z2M-Presence-Zones
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:radar
panel_title: Zone Configurator
options:
  mqtt_host: homeassistant.local
  mqtt_ws_port: 1884
  mqtt_username: ""
  mqtt_password: ""
schema:
  mqtt_host: str
  mqtt_ws_port: port
  mqtt_username: str?
  mqtt_password: password?
